/**
 * Signal Model - Trading signals (BUY/SELL/HOLD/WATCH)
 * 
 * Signals are generated by rule-based logic, then explained by Gemini AI.
 * Signals expire after 24 hours and are automatically deleted via TTL index.
 * 
 * CRITICAL: These are analysis signals, NOT execution orders.
 * Always accompanied by disclaimer that this is not financial advice.
 */

const mongoose = require('mongoose');

const signalSchema = new mongoose.Schema({
  ticker: {
    type: String,
    required: [true, 'Stock ticker is required'],
    uppercase: true,
    trim: true,
    index: true,
    match: [/^[A-Z]{1,5}$/, 'Please provide a valid stock ticker'],
  },
  signalType: {
    type: String,
    required: [true, 'Signal type is required'],
    enum: {
      values: ['BUY', 'SELL', 'HOLD', 'WATCH'],
      message: '{VALUE} is not a valid signal type',
    },
    index: true,
  },
  confidenceScore: {
    type: Number,
    required: [true, 'Confidence score is required'],
    min: [0, 'Confidence score must be between 0 and 100'],
    max: [100, 'Confidence score must be between 0 and 100'],
  },
  triggeredIndicators: [{
    name: {
      type: String,
      required: true,
    },
    value: mongoose.Schema.Types.Mixed,
    threshold: mongoose.Schema.Types.Mixed,
  }],
  aiExplanation: {
    type: String,
    required: [true, 'AI explanation is required'],
    maxlength: [1000, 'AI explanation cannot exceed 1000 characters'],
  },
  // Metadata from rule engine
  technicalScore: {
    type: Number,
    min: -100,
    max: 100,
  },
  fundamentalScore: {
    type: Number,
    min: -100,
    max: 100,
  },
  sentimentScore: {
    type: Number,
    min: -100,
    max: 100,
  },
  generatedAt: {
    type: Date,
    default: Date.now,
    index: true,
    immutable: true, // Cannot be changed after creation
  },
  expiresAt: {
    type: Date,
    default: () => new Date(Date.now() + 24 * 60 * 60 * 1000), // 24 hours
    index: true,
    immutable: true,
  },
}, {
  collection: 'signals',
});

// Compound indexes for efficient queries
signalSchema.index({ ticker: 1, generatedAt: -1 }); // Latest signal for ticker
signalSchema.index({ signalType: 1, confidenceScore: -1 }); // High-confidence signals
signalSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 }); // TTL index

// Virtual for confidence level label
signalSchema.virtual('confidenceLevel').get(function() {
  if (this.confidenceScore >= 80) return 'Very High';
  if (this.confidenceScore >= 60) return 'High';
  if (this.confidenceScore >= 40) return 'Moderate';
  return 'Low';
});

// Always include virtuals in JSON output
signalSchema.set('toJSON', { virtuals: true });

module.exports = mongoose.model('Signal', signalSchema);
